### ISSUE TITLE
Optionally replace components without pruning

### ISSUE THREAD

**Issue by saftle** [arenatemp/stable-diffusion-webui-model-toolkit#1]
A great use-case would be the ability to import the VAE, as an example, without pruning the junk. This way both the unpruned and pruned files could contain the VAE.

Otherwise you have to explain to your users that the external VAE is only required with the unpruned file.

**Comment by arenasys** [comment]
why are you distributing a model with junk in it. i can only guess you want to keep EMA data, which is pointless to do in every situation.
