### ISSUE TITLE
Checking instruct-pix2pix models?

### ISSUE THREAD

**Issue by Jonseed** [arenatemp/stable-diffusion-webui-model-toolkit#10]
Can this tool be used on instruct-pix2pix models?

When I load the original instruct-pix2pix-00-22000.safetensors model, it says that it is missing a UNET (CLIP and VAE are "broken"), and out of 1831 keys (7.17GB) there are 1386 unknown (6.4GB), and 197 useless (469MB). It says it would be pruned to 159MB. That doesn't sound right.

**Comment by arenasys** [comment]
yea i will add it. another useless UNET variation yay

**Comment by arenasys** [comment]
added in 7136a7122da6e5724c47679af37cf5939a1a65f8
