### ISSUE TITLE
New Model Is Broken

### ISSUE THREAD

**Issue by theovercomer8** [arenatemp/stable-diffusion-webui-model-toolkit#11]
Trying to follow the readme instructions to construct a new model from components, but its broken.
I select New v1 Model and hit load. I see SD-v1 in architecture and Clip-v1, Unet-v1, Vae-v1 in Class. I leave the Clip-v1 class selected and choose a clip pt from the import list and hit import. The dropdowns refresh. Everything looks good so far:
<img width="876" alt="Screen Shot 2023-01-30 at 11 56 57 AM" src="https://user-images.githubusercontent.com/122644869/215543073-c11a8278-1d99-4908-b22b-cebe9add4cac.png">

Now, I change class to Unet-v1. The dropdowns refresh, but now the architecture is no longer New V1 Model, and the only class selection available is Clip-v1:
<img width="889" alt="Screen Shot 2023-01-30 at 11 58 43 AM" src="https://user-images.githubusercontent.com/122644869/215543456-c94caed6-a459-4eb8-b4f7-26fe96b064f1.png">

Also, should there be a way to add a missing class to a model? I have a model with no VAE that I'd like to add a VAE to, but see no way to do so.

**Comment by arenasys** [comment]
Hopefully fixed by 7136a7122da6e5724c47679af37cf5939a1a65f8.

>should there be a way to add a missing class to a model?

Using `NEW SDv1` to build it, or importing the components to an existing model.

**Comment by illtellyoulater** [comment]
where can NEW SDv1 be found? I can't find it in the dropdown?
