### ISSUE TITLE
Fixing broken model

### ISSUE THREAD

**Issue by theovercomer8** [arenatemp/stable-diffusion-webui-model-toolkit#12]
So I was hoping that your tool would be able to fix an error I'm having when I try to use it with TLB's DreamBooth script, but it doesn't appear to help.

Even after running it through your tool to fix the broken unet and clip, I still receive the following issue when the converttodiff script runs:

`File "/content/convertodiff.py", line 847, in load_models_from_stable_diffusion_checkpoint
    info = unet.load_state_dict(converted_unet_checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
	Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight", "up_blocks.0.upsamplers.0.conv.bias", "up_blocks.1.upsamplers.0.conv.weight", "up_blocks.1.upsamplers.0.conv.bias", "up_blocks.2.upsamplers.0.conv.weight", "up_blocks.2.upsamplers.0.conv.bias". 
	Unexpected key(s) in state_dict: "up_blocks.0.attentions.2.conv.bias", "up_blocks.0.attentions.2.conv.weight". 
`

Anything that could be done to help?

**Comment by arenasys** [comment]
when you load the model does it detect it as SD-v1?

**Comment by theovercomer8** [comment]
Yes

**Comment by arenasys** [comment]
This extension will only report the model as SDv1 if it has every required tensor and they all have the correct shape. Your problem likely is with the dreambooth code acting up.
