### ISSUE TITLE
Extracting full models

### ISSUE THREAD

**Issue by personxyz** [arenatemp/stable-diffusion-webui-model-toolkit#13]
Hi, 

Thanks for this extension, it's got some really powerful features.

You stated that Import can extract components from full models such as CLIPs. What about extracting full models? 

I downloaded a model merge yesterday containing 2 different models. I'm only interested in one of those models but couldn't find a download link containing just it. 

Hence my plan is to extract the model I like from the model merge. Would such a thing be possible with your extension? If it is could you please tell me the steps I'd need to to take.

Thanks

**Comment by arenasys** [comment]
A merged model does not contain an intact copy of the original models, they have been merged into a new model.

**Comment by personxyz** [comment]
Damn, I guess this is a dead-end then. Thanks anyway.
