### ISSUE TITLE
How to just prune a model?

### ISSUE THREAD

**Issue by Nacurutu** [arenatemp/stable-diffusion-webui-model-toolkit#15]
I just want to prune models without adding the vae file, or, to prune a model that doesn't use a VAE, how can I do that? 
Also, how to save the model as a safetensor?

You just have the instructions to merge the VAE.

```
Easy way, replace the VAE directly:

1. Select Anything-v3.0.ckpt from the source dropdown, press Load.
2. Change to the Advanced tab.
3. Select the class VAE-v1 and leave the component on auto
4. Select Anything-v3.0.vae.ckpt from the import dropdown, press Import.
5. Change the model name to something appropriate like Anything-v3.0.safetensors
6. Press Save.
```
Could you please add a tutorial for dummies like me? 
(better if u add some images)

Thanks in advance...

**Comment by arenasys** [comment]
models get pruned automatically when you save and if the filename ends with .safetensors it will be saved as safetensors.
so just loading and saving the model is enough

**Comment by Nacurutu** [comment]
> models get pruned automatically when you save and if the filename ends with .safetensors it will be saved as safetensors. so just loading and saving the model is enough

oh, ok, thank you very much for your answer, and also thank you for this amazing tool!

As I said, I always need something for dummies. :p
