### ISSUE TITLE
Can I import the CLIP-v2 module from SD-v2 into the SD-v1 model?

### ISSUE THREAD

**Issue by xiaoyoucheng** [arenatemp/stable-diffusion-webui-model-toolkit#23]
Can I import the clip-v2 module from SD-V2 into the SD-V1 model?

![image](https://user-images.githubusercontent.com/33143581/219846123-51108b0a-ceec-4b72-bc57-4913effb7d9b.png)

**Comment by arenasys** [comment]
no, they are different architectures (CLIP ViT-L/14 vs OpenCLIP-ViT/H).

**Comment by CyberLykan** [comment]
What about converting a V2 UNET to V1 and vice-versa?
