### ISSUE TITLE
why not add this to the official extension index?

### ISSUE THREAD

**Issue by illtellyoulater** [arenatemp/stable-diffusion-webui-model-toolkit#24]
I only have that question :)

**Comment by arenasys** [comment]
I cant. If someone with permission adds it though that would be great.

**Comment by nonnonstop** [comment]
@arenatemp You can add at [AUTOMATIC1111/stable-diffusion-webui-extensions](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions).

**Comment by arenasys** [comment]
done
