### ISSUE TITLE
Autoprune naming issue

### ISSUE THREAD

**Issue by Miyuutsu** [arenatemp/stable-diffusion-webui-model-toolkit#27]
Heyo. Tried out the autoprune today, works wonderfully, but I noticed a slight naming issue. Thankfully no files were lost since it appends `(1)`, `(2)`, etc. but it seems to trim file names down to the first `.` instead of the last one. 

For example if I have a file named `my.model.for.images.safetensors` it will become `my.safetensors`.

**Comment by arenasys** [comment]
fixed by d20eb4ecb230d6926f0df80524509ca8d1595819
