### ISSUE TITLE
Ignore case while sorting

### ISSUE THREAD

**Issue by DominikDoom** [arenatemp/stable-diffusion-webui-model-toolkit#3]
Pythons sorted() has the strange default of putting uppercase A-Z completely before lowercase a-z, instead of mixing them.
At least for UI display in the dropdown this is pretty confusing.

Simple fix is just to use `sorted([...], key=lambda x: x.lower())`, or as the webui does it for the main model list:
```python
def checkpoint_tiles(): 
    convert = lambda name: int(name) if name.isdigit() else name.lower()
    alphanumeric_key = lambda key: [convert(c) for c in re.split('([0-9]+)', key)]
    return sorted([x.title for x in checkpoints_list.values()], key = alphanumeric_key)
```

**Comment by arenasys** [comment]
fixed by 16128c8c5c4415a2746b601843d179302e5ac220
