### ISSUE TITLE
[Feature Request] Support SD2 inpainting model

### ISSUE THREAD

**Issue by SLAPaper** [arenatemp/stable-diffusion-webui-model-toolkit#30]
Now it recognize SD2 inpainting model (https://huggingface.co/stabilityai/stable-diffusion-2-inpainting) as broken ones
![image](https://user-images.githubusercontent.com/7543632/236126244-ea1167c1-5e9a-4b69-81c6-a8a47b2f6b57.png)

**Comment by arenasys** [comment]
072e56a7b61e59ef845210fa875d18e3457d966d
