### ISSUE TITLE
sorry not actually an issue but there is no question area. How can I delete "junk data" but leave precission data? Hands are worse in prunned model

### ISSUE THREAD

**Issue by dilectiogames** [arenatemp/stable-diffusion-webui-model-toolkit#33]
If I delete both then I'm seeing a clear deterioration in the hands area. maybe if I get rid of this "junk data" whatever that is maybe I can keep the hands quality.

anyway, what is this "junk data"? how can I check what is inside?

**Comment by arenasys** [comment]
'clear deterioration in the hands area'
you are imagining things

'what is this "junk data"?'
unknown keys are listed in the advanced tab
