### ISSUE TITLE
How to use on CIVITAI models like Realistic Vision for finetuning Textual Inversion

### ISSUE THREAD

**Issue by sarmientoj24** [arenatemp/stable-diffusion-webui-model-toolkit#38]
They are usually 2GB in size. And they are generating images like these.

![image](https://github.com/arenasys/stable-diffusion-webui-model-toolkit/assets/8830319/cae482ec-7f89-49a4-9b9e-8369d0b61839)

**Comment by arenasys** [comment]
this extension does no fine-tuning, you are confused
