### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by zethfoxster** [arenatemp/stable-diffusion-webui-model-toolkit#47]
title said it all....

**Comment by arenasys** [comment]
yep, i dont use a1111 or its offshoots anymore.

**Comment by zethfoxster** [comment]
> yep, i dont use a1111 or its offshoots anymore.

well i would like to thank you for the time you spent in this project. for what its worth it was the best in its class :)

**Comment by cse84** [comment]
Can you point to any replacement? A web search still leads to this project as the right tool for extracting/replacing components of a checkpoint and the Readme contains no indication that the project is dead or obsolete.

**Comment by cse84** [comment]
To answer my own question: ComfyUI has (under "loaders", under "advanced"->"loaders" and under "advanced"->"model_merging") nodes that can be combined to do many of the same tasks that this project does. These nodes are "CLIPSave", "VAESave", "ModelSave", "LoadCLIP", "Load Diffusion Model", "Load VAE", "SaveCheckpoint" and "Load Checkpoint".

**Comment by zethfoxster** [comment]
> To answer my own question: ComfyUI has (under "loaders", under "advanced"->"loaders" and under "advanced"->"model_merging") nodes that can be combined to do many of the same tasks that this project does. These nodes are "CLIPSave", "VAESave", "ModelSave", "LoadCLIP", "Load Diffusion Model", "Load VAE", "SaveCheckpoint" and "Load Checkpoint".

this is an option, if you like SpaghettiUi...I would love to see webui version revived someday
