### ISSUE TITLE
"Fix broken CLIP position IDs" option?

### ISSUE THREAD

**Issue by Jonseed** [arenatemp/stable-diffusion-webui-model-toolkit#6]
I seem to have a lot of models with broken CLIP. On the basic screen it says: "CLIP has incorrect positions, missing: 1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 24, 26, 27, 28, 29, 31, 32, 33, 34, 37, 38, 39, 41, 42, 43, 44, 46, 47, 48, 49, 51, 52, 53, 54, 56, 57, 59, 61, 62, 64, 65, 66, 67, 68, 69, 71, 73, 74, 76."

But I don't see an option to "Fix broken CLIP position IDs." Where is this option?

**Comment by arenasys** [comment]
in settings...

**Comment by illtellyoulater** [comment]
in which way fixing this is going to improve the output?
