### ISSUE TITLE
Unknown keys?

### ISSUE THREAD

**Issue by Jonseed** [arenatemp/stable-diffusion-webui-model-toolkit#7]
My models have a lot of unknown keys, like: "embedding_manager.embedder.transformer.text_model.encoder.layers.0.layer_norm2.bias (768,)"

What are these? It looks like they are a part of the text encoder? CLIP?

What does this tool do with these unknown keys?

**Comment by arenasys** [comment]
it deletes them, idk what those are from ive never seen them before

**Comment by Jonseed** [comment]
ok... but surely there is a reason they are there?

**Comment by arenasys** [comment]
probably left over from some TI training script. they are not used for inference at all
