### ISSUE TITLE
Warning after activating extension with check mark

### ISSUE THREAD

**Issue by f-rank** [arenatemp/stable-diffusion-webui-model-toolkit#8]
Just a heads up, when check mark is on in extensions and restarting UI, this is thrown:

Closing server running on port: 7860
Restarting UI...
d:\WORK\conda_envs\automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Blocks, please remove them: {'variant': 'compact'}
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

Don't know if it is relevant.
I am on auto web ui Commit hash: aa6e55e00140da6d73d3d360a5628c1b1316550d
Had to roll back a bit because there's a ckpt problem with defaults, not reading metadata, time of generation model switch, etc.
But this got thrown on both commits.

**Comment by arenasys** [comment]
Check what Gradio version you have, I dont see the error with `gradio: 3.16.2` (the WebUIs current supported version)

**Comment by f-rank** [comment]
> Check what Gradio version you have, I dont see the error with `gradio: 3.16.2` (the WebUIs current supported version)

gradio: 3.16.2

**Comment by arenasys** [comment]
damn. well its just a depreciation warning, can ignore it
